---
- name: Test Ansible on Azure base VM
  hosts: all
  gather_facts: yes
  tasks:
    - name: Set facts
      set_fact:
        demo_folder: 'C:\UiPath\Demos\'
        temp_folder: 'C:\Temp'
        config_folder: 'C:\UiPath\config\'
        git_repos: "{{ lookup('env','GIT_REPO_SOURCE_TESTING').split(',') }}"
        git_token: "{{ lookup('env', 'GIT_TOKEN') }}"
        blob_conn_string: "{{ lookup('env', 'BLOB_CONN_STRING') }}"
      no_log: True

    # Create required folders
    - name: Create demo folder
      win_file:
        path: "{{ demo_folder }}"
        state: directory

    - name: Create temp folder
      win_file:
        path: "{{ temp_folder }}"
        state: directory

    - name: Create config folder
      win_file:
        path: "{{ config_folder }}"
        state: directory

    - name: Copy PowerShell helper scripts to C:\Temp
      win_copy:
        src: PSscripts
        dest: "{{ temp_folder }}"

    - name: Copy Config files to C:\Temp
      win_copy:
        src: configFiles
        dest: C:\Temp

    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        pinned: yes
        state: present
        ignore_checksums: yes

    - name: Install python
      win_chocolatey:
        name: python3
        version: 3.6.8
        state: present

    - name: install pip modules
      win_shell: |
        pip install pymongo
        pip install requests
        pip install azure-keyvault-secrets
        pip install azure-mgmt-resource
        pip install azure-keyvault-keys
        pip install azure-keyvault-certificates
        pip install azure-identity

    - name: Add Azure Storage PowerShell module
      win_psmodule:
        name: Azure.Storage
        state: present

    - name: Install UiPath Studio
      win_package:
        path: https://download.uipath.com/versions/20.4.1/UiPathStudio.msi
        arguments:
        - /quiet
        - ADDLOCAL=DesktopFeature,Robot,Packages,Studio,StartupLauncher,RegisterService,JavaBridge,ChromeExtension
        state: present
        product_id: '{3067A978-2709-4976-8F50-6CD65A1DC380}'
        log_path: C:\log.txt

    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: UiRobotSvc
        start_mode: auto
        state: started

    - name: Install git client
      win_chocolatey:
        name:
          - git
        state: present

    - name: Git clone demo repositories
      win_shell: |
        cd {{demo_folder}}
        git clone https://{{git_token}}@github.com/{{ item }}
      loop: "{{ git_repos }}"
      no_log: True
      args:
        creates: C:\UiPath\Demos\uipath-testing-demos

    #Install SAP Components
    - name: Install SAP Components
      win_shell: C:\Temp\PSscripts\Install-SAPGUI.ps1 -ConnectionString "{{ blob_conn_string }}"
      args:
        creates: "C:\\Program Files (x86)\\SAP"
      no_log: True

    # install Jenkins
    - name: Install Jenkins
      win_chocolatey:
        name:
          - jenkins
        state: present

    # install node js
    - name: install node.js lts
      win_chocolatey:
        name:
          - nodejs-lts
        state: present

    - name: Reboot the machine with all defaults
      win_reboot:

