---
- name: Test Ansible on Azure base VM
  hosts: all
  gather_facts: yes
  tasks:
    - name: Set facts
      set_fact:
        demo_folder: 'C:\UiPath\Demos\'
        temp_folder: 'C:\Temp'
        git_repos: "{{ lookup('env','GIT_REPO_SOURCE_TESTING').split(',') }}"
        git_token: "{{ lookup('env', 'GIT_TOKEN') }}"
        license_code: "{{ lookup('env', 'TESTING_LICENSE_CODE') }}"
        blob_conn_string: "{{ lookup('env', 'BLOB_CONN_STRING') }}"
      no_log: True

    # Create required folders
    - name: Create demo folder
      win_file:
        path: "{{ demo_folder }}"
        state: directory

    - name: Create temp folder
      win_file:
        path: "{{ temp_folder }}"
        state: directory

    - name: Copy PowerShell helper scripts to C:\Temp
      win_copy:
        src: PSscripts
        dest: "{{ temp_folder }}"

    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        pinned: yes
        state: present
        ignore_checksums: yes

    - name: Install python
      win_chocolatey:
        name: python3
        version: 3.6.8
        state: present

    - name: Add Azure Storage PowerShell module
      win_psmodule:
        name: Azure.Storage
        state: present

    #Download UiPath Studio Pro
    - name: Get UiPath Pro
      win_shell: C:\Temp\PSscripts\Get-Robot.ps1 -ConnectionString "{{ blob_conn_string }}"
      no_log: True

    - name: Install UiPath Studio
      win_package:
        path: C:\Temp\UiPathStudio.msi
        arguments:
          - /quiet
          - ADDLOCAL=DesktopFeature,Robot,Packages,Studio,StartupLauncher,RegisterService,JavaBridge,ChromeExtension
        state: present
        product_id: "{CCB49257-B726-4570-B9C8-7BA2E6F7438A}"

    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: UiRobotSvc
        start_mode: auto
        state: started

    - name: Install git client
      win_chocolatey:
        name:
          - git
        state: present

    - name: Git clone demo repositories
      win_shell: |
        cd {{demo_folder}}
        git clone https://{{git_token}}@github.com/{{ item }}
      loop: "{{ git_repos }}"
      no_log: True
      args:
        creates: C:\UiPath\Demos\uipath-testing-demos

    #Install SAP Components
    - name: Install SAP Components
      win_shell: C:\Temp\PSscripts\Install-SAPGUI.ps1 -ConnectionString "{{ blob_conn_string }}"
      args:
        creates: "C:\\Program Files (x86)\\SAP"

    # install Jenkins
    - name: Install Jenkins
      win_chocolatey:
        name:
          - jenkins
        state: present

    # install node js
    - name: install node.js lts
      win_chocolatey:
        name:
          - nodejs-lts
        state: present

    - name: Reboot the machine with all defaults
      win_reboot:

      # install newman
    - name: Install "newmann" node.js package globally.
      win_shell: "npm install -g newman"

